name: Auto PR Assign

on:
  pull_request:
    types: [opened, unassigned]

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  assign:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - name: Set assignees
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event.pull_request.user.type != 'Bot' && toJSON(github.event.pull_request.assignees) == '[]' }}