name: Lint

on:
  push:
    paths:
      - .github/workflows/lint.yml
      - "**/*.py"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip lint]') }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction

      - name: flake8
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          fail_level: warning
          filter_mode: nofilter
          workdir: src

      - name: mypy
        uses: tsuyoshicho/action-mypy@v4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          filter_mode: nofilter
          workdir: src
          execute_command: 'poetry run mypy'