name: Test

on:
  push:
    paths:
      - .github/workflows/pytest.yml
      - "**/*.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip test]') }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction

      - name: pytest
        run: poetry run pytest